Los Angeles Traffic Collision

In [2]:
# Importing libraries
import pandas as pd

Loading Data

In [6]:
traffic_collision_df = pd.read_csv('data/traffic-collision-data-from-2010-to-present.csv', index_col='DR Number')
traffic_collision_df.head()

,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,Victim Age,...,Premise Description,Address,Cross Street,Location,Zip Codes,Census Tracts,Precinct Boundaries,LA Specific Plans,Council Districts,Neighborhood Councils (Certified)
DR Number,,,,,,,,,,,,,,,,,,,,,
190614534,2019-06-29T00:00:00.000,2019-06-29T00:00:00.000,1000,6,Hollywood,626,997,TRAFFIC COLLISION,NaN,NaN,...,STREET,PRIMROSE AV,VINE ST,"{'latitude': '34.1098', 'longitude': '-118.326...",24033.0,405.0,371.0,NaN,7.0,64.0
190411644,2019-06-29T00:00:00.000,2019-06-29T00:00:00.000,710,4,Hollenbeck,479,997,TRAFFIC COLLISION,NaN,25.0,...,STREET,WHITTIER BL,SPENCE ST,"{'latitude': '34.0265', 'longitude': '-118.198...",23441.0,527.0,352.0,NaN,9.0,38.0
190913064,2019-06-29T00:00:00.000,2019-06-29T00:00:00.000,710,9,Van Nuys,923,997,TRAFFIC COLLISION,NaN,35.0,...,STREET,VAN NUYS BL,VANOWEN ST,"{'latitude': '34.1939', 'longitude': '-118.448...",19733.0,236.0,290.0,NaN,3.0,18.0
191217109,2019-06-29T00:00:00.000,2019-06-29T00:00:00.000,125,12,77th Street,1245,997,TRAFFIC COLLISION,4025 3036 3004 3026 3029 3101,34.0,...,STREET,VERMONT AV,FLORENCE AV,"{'latitude': '33.9746', 'longitude': '-118.291...",23675.0,777.0,1161.0,7.0,14.0,20.0
191011660,2019-06-29T00:00:00.000,2019-06-29T00:00:00.000,40,10,West Valley,1005,997,TRAFFIC COLLISION,NaN,50.0,...,STREET,SATICOY ST,BALCOM AV,"{'latitude': '34.2084', 'longitude': '-118.520...",18909.0,253.0,914.0,NaN,2.0,12.0

Cleaning Data

In [7]:
traffic_collision_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 478415 entries, 190614534 to 100104049
Data columns (total 23 columns):
Date Reported                        478415 non-null object
Date Occurred                        478415 non-null object
Time Occurred                        478415 non-null int64
Area ID                              478415 non-null int64
Area Name                            478415 non-null object
Reporting District                   478415 non-null int64
Crime Code                           478415 non-null int64
Crime Code Description               478415 non-null object
MO Codes                             393593 non-null object
Victim Age                           400964 non-null float64
Victim Sex                           471443 non-null object
Victim Descent                       470724 non-null object
Premise Code                         478390 non-null float64
Premise Description                  478390 non-null object
Address                              478415 non-null object
Cross Street                         457148 non-null object
Location                             478415 non-null object
Zip Codes                            478018 non-null float64
Census Tracts                        471923 non-null float64
Precinct Boundaries                  475345 non-null float64
LA Specific Plans                    176007 non-null float64
Council Districts                    472739 non-null float64
Neighborhood Councils (Certified)    454497 non-null float64
dtypes: float64(8), int64(4), object(11)
memory usage: 87.6+ MB

Points to note
1. Date Reported is in string
2. Date Occurred is in string
3. Merge Date Occured and Time Occurred
4. MO Codes has NANs and list of Codes
5. Victim Sex, Descent has NANs and can be converted to category
6. Location is python's dictionary

In [10]:
traffic_collision_df.loc[:,['Victim Age','Victim Sex','Victim Descent','Premise Code']].head()

           Victim Age Victim Sex Victim Descent  Premise Code
DR Number
190614534         NaN          M              W         101.0
190411644        25.0          M              H         101.0
190913064        35.0          M              H         101.0
191217109        34.0          M              B         101.0
191011660        50.0          F              H         101.0